# Generated by Django 3.1.5 on 2021-02-07 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('genre_for', models.CharField(choices=[('mv', 'movie'), ('tv', 'tv')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='flixmedia.Genre')),
            ],
            options={
                'ordering': ['date_uploaded'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('season_number', models.IntegerField()),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='flixmedia.tv')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='flixmedia.Genre')),
            ],
            options={
                'ordering': ['date_uploaded'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('episode_number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='flixmedia.season')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='tv',
            constraint=models.UniqueConstraint(fields=('id', 'genres'), name='tv_id_genre_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('id', 'genres'), name='movie_id_genre_unique_constraint'),
        ),
    ]
