# Generated by Django 3.1.5 on 2021-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(unique=True),
        ),
    ]
