# Generated by Django 3.1.5 on 2021-02-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixfeed', '0001_initial'),
        ('flixmedia', '0002_auto_20210208_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ManyToManyField(related_name='movie', to='flixfeed.Rate'),
        ),
        migrations.AddField(
            model_name='tv',
            name='rating',
            field=models.ManyToManyField(related_name='tv', to='flixfeed.Rate'),
        ),
    ]
