# Generated by Django 3.1.5 on 2021-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixfeed', '0002_auto_20210209_2230'),
        ('flixmedia', '0003_auto_20210209_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='rating',
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.ManyToManyField(related_name='episode_ratings', to='flixfeed.Rate'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.ManyToManyField(related_name='movie_ratings', to='flixfeed.Rate'),
        ),
    ]
