# Generated by Django 3.1.5 on 2021-02-09 03:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='rated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
